name: test

on: [push, pull_request]

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      -
        name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: localhost:5000/alexmisk/yt-downloader:latest
      -
        name: Checkout
        uses: actions/checkout@v2.3.1
      -
        name: Install test suite
        run: |
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
      -
         name: Run tests
         run: |
           bats tests/*
